In [12]:
import numpy as np
import pandas as pd

In [13]:

df = pd.Series([1,2,3,4,5])
df1 = pd.Series([1,2,3,4,5])


result = df + df1
print(result)

0     2
1     4
2     6
3     8
4    10
dtype: int64

In [14]:
df1 = pd.Series([1,2,3,4,5])

df2 = pd.Series([1,22,3,41,5])

result = (df1==df2)
print(result)

0     True
1    False
2     True
3    False
4     True
dtype: bool

In [15]:
hf = {'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}

result = pd.Series(hf)

print(result)

a    100
b    200
c    300
d    400
e    800
dtype: int64

In [16]:
data = [10, 20, 30, 40, 50]

result = pd.Series(data1)

print(result)

NameError: name 'data1' is not defined

In [ ]:
data_given = ([100,200,'python',300,400])

result = s2 = pd.to_numeric(pd.Series(data_given), errors='coerce')

print(result)

0    100.0
1    200.0
2      NaN
3    300.0
4    400.0
dtype: float64

In [ ]:
hello = [
	['Red', 'Green', 'White'],
	['Red', 'Black'],
	['Yellow']
]

result = pd.Series(hello)

print(result)

0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: object

In [ ]:
s = pd.Series([1, 2, 'python', 4, 'gandu'])


s_add = pd.concat([s, pd.Series([100, 200])], ignore_index=True)


print(s_add)

0         1
1         2
2    python
3         4
4     gandu
5       100
6       200
dtype: object

In [ ]:
s1 = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]})

In [ ]:
s1

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83

In [ ]:
details = pd.DataFrame({'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
                        'Age': [27, 24, 22, 32],
                        'Address': ['Delhi', 'Kanpur', 'Allahabad', 'Kannauj'],
                        'Qualification': ['Msc', 'MA', 'MCA', 'Phd']})

In [ ]:
details

     Name  Age    Address Qualification
0     Jai   27      Delhi           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannauj           Phd

In [ ]:
m_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}


lables = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(m_data, index=lables)

In [ ]:
df[['name', 'score','attempts', ]]

        name  score  attempts
a  Anastasia   12.5         1
b       Dima    9.0         3
c  Katherine   16.5         2
d      James    NaN         3
e      Emily    9.0         2
f    Michael   20.0         3
g    Matthew   14.5         1
h      Laura    NaN         1
i      Kevin    8.0         2
j      Jonas   19.0         1

In [ ]:

exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}


lables = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data, index=lables)

In [ ]:
df[df['attempts']>2]

      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes

In [ ]:

exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}


df = pd.DataFrame(np.arange(10).reshape(5,2), columns=['col1', 'col2'])

In [ ]:
df

   col1  col2
0     0     1
1     2     3
2     4     5
3     6     7
4     8     9

In [20]:
import numpy as np
import pandas as pd

In [19]:
exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}

lables = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


df = pd.DataFrame(exam_data,index = lables)

In [24]:
df['score'].mean()

np.float64(13.5625)

In [25]:
df

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

In [26]:
df.loc['k'] = ['suresh', 15.5, 1, 'yes']

print(df)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
k     suresh   15.5         1     yes

In [27]:
df.drop('k', inplace=True)

In [28]:
df

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

In [36]:
d = {'col1': [1, 2, 3], 'col2': [4, 5, 6], 'col3': [7, 8, 9]}
df = pd.DataFrame(data=d)


print(df)


### now to rename the columns name

pk =df.rename(columns ={'col1':'column1', 'col2':'column2', 'col3':'column3'}, inplace=True)
print(df)

   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6     9
   column1  column2  column3
0        1        4        7
1        2        5        8
2        3        6        9

In [38]:
d = {'col1': [1, 2, 3], 'col2': [4, 5, 6], 'col3': [7, 8, 9]}
df = pd.DataFrame(data=d)


print("original data frame")
print(df)


df.loc[df['col1'] == 4]

original data frame
   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6     9

Empty DataFrame
Columns: [col1, col2, col3]
Index: []

In [1]:
import numpy as np
import pandas as pd

In [5]:
df = pd.DataFrame({
    'school_code': ['s001','s002','s003','s001','s002','s004'],
    'class': ['V', 'V', 'VI', 'VI', 'V', 'VI'],
    'name': ['Alberto Franco','Gino Mcneill','Ryan Parkes', 'Eesha Hinton', 'Gino Mcneill', 'David Parkes'],
    'date_Of_Birth': ['15/05/2002','17/05/2002','16/02/1999','25/09/1998','11/05/2002','15/09/1997'],
    'weight': [35, 32, 33, 30, 31, 32],
    'address': ['street1', 'street2', 'street3', 'street1', 'street2', 'street4'],
    't_id':['t1', 't2', 't3', 't4', 't5', 't6']})


print("default data frame")

print(df.head(10))

print("group by school code")
df1 = df.set_index('school_code')
print(df1)


df2 = df.set_index('t_id')
print(df2)

default data frame
  school_code class            name date_Of_Birth  weight  address t_id
0        s001     V  Alberto Franco    15/05/2002      35  street1   t1
1        s002     V    Gino Mcneill    17/05/2002      32  street2   t2
2        s003    VI     Ryan Parkes    16/02/1999      33  street3   t3
3        s001    VI    Eesha Hinton    25/09/1998      30  street1   t4
4        s002     V    Gino Mcneill    11/05/2002      31  street2   t5
5        s004    VI    David Parkes    15/09/1997      32  street4   t6
group by school code
            class            name date_Of_Birth  weight  address t_id
school_code
s001            V  Alberto Franco    15/05/2002      35  street1   t1
s002            V    Gino Mcneill    17/05/2002      32  street2   t2
s003           VI     Ryan Parkes    16/02/1999      33  street3   t3
s001           VI    Eesha Hinton    25/09/1998      30  street1   t4
s002            V    Gino Mcneill    11/05/2002      31  street2   t5
s004           VI    David Parkes    15/09/1997      32  street4   t6
     school_code class            name date_Of_Birth  weight  address
t_id
t1          s001     V  Alberto Franco    15/05/2002      35  street1
t2          s002     V    Gino Mcneill    17/05/2002      32  street2
t3          s003    VI     Ryan Parkes    16/02/1999      33  street3
t4          s001    VI    Eesha Hinton    25/09/1998      30  street1
t5          s002     V    Gino Mcneill    11/05/2002      31  street2
t6          s004    VI    David Parkes    15/09/1997      32  street4

In [ ]:
df = pd.DataFrame({
    'school_code': ['s001','s002','s003','s001','s002','s004'],
    'class': ['V', 'V', 'VI', 'VI', 'V', 'VI'],
    'name': ['Alberto Franco','Gino Mcneill','Ryan Parkes', 'Eesha Hinton', 'Gino Mcneill', 'David Parkes'],
    'date_Of_Birth': ['15/05/2002','17/05/2002','16/02/1999','25/09/1998','11/05/2002','15/09/1997'],
    'weight': [35, 32, 33, 30, 31, 32],
    'address': ['street1', 'street2', 'street3', 'street1', 'street2', 'street4'],
    't_id':['t1', 't2', 't3', 't4', 't5', 't6']})


df1 = df.set_index(['school_code','t_id'])
print(df1)


df = df.set_index(pd.Index([0,1,2,3,4,5]))

print(df)

                 class            name date_Of_Birth  weight  address
school_code t_id
s001        t1       V  Alberto Franco    15/05/2002      35  street1
s002        t2       V    Gino Mcneill    17/05/2002      32  street2
s003        t3      VI     Ryan Parkes    16/02/1999      33  street3
s001        t4      VI    Eesha Hinton    25/09/1998      30  street1
s002        t5       V    Gino Mcneill    11/05/2002      31  street2
s004        t6      VI    David Parkes    15/09/1997      32  street4
  school_code class            name date_Of_Birth  weight  address t_id
0        s001     V  Alberto Franco    15/05/2002      35  street1   t1
1        s002     V    Gino Mcneill    17/05/2002      32  street2   t2
2        s003    VI     Ryan Parkes    16/02/1999      33  street3   t3
3        s001    VI    Eesha Hinton    25/09/1998      30  street1   t4
4        s002     V    Gino Mcneill    11/05/2002      31  street2   t5
5        s004    VI    David Parkes    15/09/1997      32  street4   t6

In [21]:
df = pd.DataFrame({
    'school_code': ['s001','s002','s003','s001','s002','s004'],
    'class': ['V', 'V', 'VI', 'VI', 'V', 'VI'],
    'name': ['Alberto Franco','Gino Mcneill','Ryan Parkes', 'Eesha Hinton', 'Gino Mcneill', 'David Parkes'],
    'date_Of_Birth': ['15/05/2002','17/05/2002','16/02/1999','25/09/1998','11/05/2002','15/09/1997'],
    'weight': [35, 32, 33, 30, 31, 32],
    'address': ['street1', 'street2', 'street3', 'street1', 'street2', 'street4'],
    't_id':['t1', 't2', 't3', 't4', 't5', 't6']})


print("default data frame ")

print(df.head(10))

df1 = df.set_index('t_id')

print(df1)

df2 = df1.reset_index(inplace=True)

print(df2)

default data frame
  school_code class            name date_Of_Birth  weight  address t_id
0        s001     V  Alberto Franco    15/05/2002      35  street1   t1
1        s002     V    Gino Mcneill    17/05/2002      32  street2   t2
2        s003    VI     Ryan Parkes    16/02/1999      33  street3   t3
3        s001    VI    Eesha Hinton    25/09/1998      30  street1   t4
4        s002     V    Gino Mcneill    11/05/2002      31  street2   t5
5        s004    VI    David Parkes    15/09/1997      32  street4   t6
     school_code class            name date_Of_Birth  weight  address
t_id
t1          s001     V  Alberto Franco    15/05/2002      35  street1
t2          s002     V    Gino Mcneill    17/05/2002      32  street2
t3          s003    VI     Ryan Parkes    16/02/1999      33  street3
t4          s001    VI    Eesha Hinton    25/09/1998      30  street1
t5          s002     V    Gino Mcneill    11/05/2002      31  street2
t6          s004    VI    David Parkes    15/09/1997      32  street4
None