In [1]:
import numbers as np
import pandas as pd

merge 2 data frame

In [13]:
df1_merge = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35]
})


df2_merge = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Salary': [50000, 60000, 70000]
})

In [14]:
df1_merge

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [15]:
df2_merge

      Name  Salary
0    Alice   50000
1      Bob   60000
2  Charlie   70000

commmon id ke badaulat krn hoga jo krna hoga

In [17]:
pd.merge(df1_merge, df2_merge, on='Name',how='inner')

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000

In [18]:
pd.merge(df1_merge, df2_merge, on='Name',how='outer')

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000