In [2]:
import pandas as pd
import numpy as np

In [8]:
label = ['a','b','c']
my_list = [1,2,3]

arr = np.array([10,20,30])
d = {'a':10,'b':20,'c':30}

In [9]:
pd.Series(my_list, index = label)
pd.Series(d)

a    10
b    20
c    30
dtype: int64

DATA FRAMES

In [2]:
import numpy as np
import pandas as pd

In [3]:
data = {
    'name':['ayush','anya','megha ', 'priya'],
    'age':[18,22,12,37],
    'city':['london', 'patna','bihar', 'delhi'],
    'salary': [12000000,2300,20200,2889300]
    
    
}

df =pd.DataFrame(data)

In [4]:
data_list= [
    ['ayush',19,'new york',12000000],
    ['shivam',18,'new york',1200000],
    ['diksha',20,'london',12000],
]



df2 =  pd.DataFrame(data_list)
columns = ["name", "age","city","salary"]

df2 =  pd.DataFrame(data_list,columns=columns)

SELECTION AND INDEXING OF COLUMNS

In [ ]:
df[['name','city']]

KeyError: "['city'] not in index"

CREATING A NEW COLUMNS

In [7]:
df2["designation"] = ["doctor", "eng", "doc"]

In [42]:
df2

     name  age
0   ayush   19
1  shivam   18
2  diksha   20

REMOVE A COLUMN

In [40]:
df2

     name  age
0   ayush   19
1  shivam   18
2  diksha   20

CONDITIONAL SELECTION

In [44]:
df2[df2["age"]>18]

     name  age
0   ayush   19
2  diksha   20

In [ ]:
df2[df2["age"]>18 & df2[""]]