In [1]:
import numpy as np
import pandas as pd

FIND MISSING DATA

In [2]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 32, np.nan, 47],
    'City': ['New York', 'Paris', None, 'London'],
    'Score': [85.5, np.nan, 91.2, 78.0]
}

    
df2= pd.DataFrame(data)

In [3]:
df2

      Name   Age      City  Score
0    Alice  25.0  New York   85.5
1      Bob  32.0     Paris    NaN
2  Charlie   NaN       NaN   91.2
3    David  47.0    London   78.0

In [5]:
df2.isna().sum()

Name     0
Age      1
City     1
Score    1
dtype: int64

In [6]:
df2.isna().any()

Name     False
Age       True
City      True
Score     True
dtype: bool

REMOVING MISSING DATA

In [7]:
df2.dropna()

    Name   Age      City  Score
0  Alice  25.0  New York   85.5
3  David  47.0    London   78.0

In [10]:
df2.fillna(0)

      Name   Age      City  Score
0    Alice  25.0  New York   85.5
1      Bob  32.0     Paris    0.0
2  Charlie   0.0         0   91.2
3    David  47.0    London   78.0