In [185]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')

## losading the dta set

In [186]:
df = pd.read_csv('C:\CODING\MACHINE LEARNING\ML_HEART _DEASES_ PREDECTION_FULL _APP\practice py\heart.csv')

In [187]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

## target we have to predict heart deasis

## now doing eda process

In [188]:
df.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [189]:
df.duplicated().sum()

np.int64(0)

In [190]:
df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [191]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    str
 2   ChestPainType   918 non-null    str
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    str
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    str
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    str
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), str(5)
memory usage: 86.2 KB

In [192]:
import sheryanalysis
sheryanalysis.analyze(df)

🔍 Basic Analysis Report
------------------------------------------------------------
📏 Shape: (918, 12)
🧱 Columns: ['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS', 'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope', 'HeartDisease']

✅ No null values found

🔠 Categorical Columns: ['Sex', 'ChestPainType', 'FastingBS', 'RestingECG', 'ExerciseAngina', 'ST_Slope', 'HeartDisease']

🔢 Numerical Columns: ['Age', 'RestingBP', 'Cholesterol', 'MaxHR', 'Oldpeak']

{'shape': (918, 12),
 'columns': ['Age',
  'Sex',
  'ChestPainType',
  'RestingBP',
  'Cholesterol',
  'FastingBS',
  'RestingECG',
  'MaxHR',
  'ExerciseAngina',
  'Oldpeak',
  'ST_Slope',
  'HeartDisease'],
 'dtypes': {'Age': dtype('int64'),
  'Sex': <StringDtype(storage='python', na_value=nan)>,
  'ChestPainType': <StringDtype(storage='python', na_value=nan)>,
  'RestingBP': dtype('int64'),
  'Cholesterol': dtype('int64'),
  'FastingBS': dtype('int64'),
  'RestingECG': <StringDtype(storage='python', na_value=nan)>,
  'MaxHR': dtype('int64'),
  'ExerciseAngina': <StringDtype(storage='python', na_value=nan)>,
  'Oldpeak': dtype('float64'),
  'ST_Slope': <StringDtype(storage='python', na_value=nan)>,
  'HeartDisease': dtype('int64')},
 'null_counts': {'Age': 0,
  'Sex': 0,
  'ChestPainType': 0,
  'RestingBP': 0,
  'Cholesterol': 0,
  'FastingBS': 0,
  'RestingECG': 0,
  'MaxHR': 0,
  'ExerciseAngina': 0,
  'Oldpeak': 0,
  'ST_Slope': 0,
  'HeartDisease': 0},
 'total_rows': 918,
 'column_types': {'categorical': ['Sex',
   'ChestPainType',
   'FastingBS',
   'RestingECG',
   'ExerciseAngina',
   'ST_Slope',
   'HeartDisease'],
  'numerical': ['Age', 'RestingBP', 'Cholesterol', 'MaxHR', 'Oldpeak'],
  'datetime': [],
  'text': []}}

## doing one_hot_encoding

In [193]:
x = df.drop(['HeartDisease'],axis=1)
y = df['HeartDisease']

In [194]:
x

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up
...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up

In [195]:
y

0      0
1      1
2      0
3      1
4      0
      ..
913    1
914    1
915    1
916    1
917    0
Name: HeartDisease, Length: 918, dtype: int64

## checking the values.counts of str

In [196]:
df['ChestPainType'].value_counts()

ChestPainType
ASY    496
NAP    203
ATA    173
TA      46
Name: count, dtype: int64

In [197]:
df['RestingECG'].value_counts()

RestingECG
Normal    552
LVH       188
ST        178
Name: count, dtype: int64

In [198]:
df['ExerciseAngina'].value_counts()

ExerciseAngina
N    547
Y    371
Name: count, dtype: int64

In [199]:
df['ST_Slope'].value_counts()

ST_Slope
Flat    460
Up      395
Down     63
Name: count, dtype: int64

## applying data cleaning and preporessing(( means aplyng one_hot_encoing & label_encoding))

In [200]:
one_hot_encoding = pd.get_dummies(x,columns=['ChestPainType','RestingECG','ExerciseAngina','ST_Slope','Sex'],drop_first=True)

In [201]:
one_hot_encoding.head()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up,Sex_M
0,40,140,289,0,172,0.0,True,False,False,True,False,False,False,True,True
1,49,160,180,0,156,1.0,False,True,False,True,False,False,True,False,False
2,37,130,283,0,98,0.0,True,False,False,False,True,False,False,True,True
3,48,138,214,0,108,1.5,False,False,False,True,False,True,True,False,False
4,54,150,195,0,122,0.0,False,True,False,True,False,False,False,True,True

In [202]:
one_hot_encoding = one_hot_encoding.astype(int)

In [203]:
one_hot_encoding.head()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up,Sex_M
0,40,140,289,0,172,0,1,0,0,1,0,0,0,1,1
1,49,160,180,0,156,1,0,1,0,1,0,0,1,0,0
2,37,130,283,0,98,0,1,0,0,0,1,0,0,1,1
3,48,138,214,0,108,1,0,0,0,1,0,1,1,0,0
4,54,150,195,0,122,0,0,1,0,1,0,0,0,1,1

## doing standard scaling with the help of one_hot_encoding

In [204]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [205]:
sheryanalysis.analyze(df)

🔍 Basic Analysis Report
------------------------------------------------------------
📏 Shape: (918, 12)
🧱 Columns: ['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS', 'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope', 'HeartDisease']

✅ No null values found

🔠 Categorical Columns: ['Sex', 'ChestPainType', 'FastingBS', 'RestingECG', 'ExerciseAngina', 'ST_Slope', 'HeartDisease']

🔢 Numerical Columns: ['Age', 'RestingBP', 'Cholesterol', 'MaxHR', 'Oldpeak']

{'shape': (918, 12),
 'columns': ['Age',
  'Sex',
  'ChestPainType',
  'RestingBP',
  'Cholesterol',
  'FastingBS',
  'RestingECG',
  'MaxHR',
  'ExerciseAngina',
  'Oldpeak',
  'ST_Slope',
  'HeartDisease'],
 'dtypes': {'Age': dtype('int64'),
  'Sex': <StringDtype(storage='python', na_value=nan)>,
  'ChestPainType': <StringDtype(storage='python', na_value=nan)>,
  'RestingBP': dtype('int64'),
  'Cholesterol': dtype('int64'),
  'FastingBS': dtype('int64'),
  'RestingECG': <StringDtype(storage='python', na_value=nan)>,
  'MaxHR': dtype('int64'),
  'ExerciseAngina': <StringDtype(storage='python', na_value=nan)>,
  'Oldpeak': dtype('float64'),
  'ST_Slope': <StringDtype(storage='python', na_value=nan)>,
  'HeartDisease': dtype('int64')},
 'null_counts': {'Age': 0,
  'Sex': 0,
  'ChestPainType': 0,
  'RestingBP': 0,
  'Cholesterol': 0,
  'FastingBS': 0,
  'RestingECG': 0,
  'MaxHR': 0,
  'ExerciseAngina': 0,
  'Oldpeak': 0,
  'ST_Slope': 0,
  'HeartDisease': 0},
 'total_rows': 918,
 'column_types': {'categorical': ['Sex',
   'ChestPainType',
   'FastingBS',
   'RestingECG',
   'ExerciseAngina',
   'ST_Slope',
   'HeartDisease'],
  'numerical': ['Age', 'RestingBP', 'Cholesterol', 'MaxHR', 'Oldpeak'],
  'datetime': [],
  'text': []}}

## creating model with all five models

In [234]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

from sklearn.metrics import f1_score,accuracy_score,classification_report,confusion_matrix
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

In [207]:
X_train, X_test, y_train, y_test = train_test_split(one_hot_encoding, y, test_size=0.33, random_state=42)

In [208]:
model_line_reg = LinearRegression()
model_line_reg.fit(X_train,y_train)

LinearRegression()

In [209]:
y_pred_lin_reg = model_line_reg.predict(X_test)

In [210]:
y_pred_lin_reg

array([-0.01466054,  0.33950833,  0.98373752,  1.01983552,  0.03570934,
        0.80554318,  0.75597852,  0.10260452,  0.70921495,  0.85204788,
        0.581478  ,  0.12540489,  0.67526445,  0.06680815,  0.85628395,
        0.53590241, -0.05238685,  0.7147684 ,  0.70610956,  0.2813792 ,
        0.65031133,  0.77357483,  0.01383641,  0.63146834,  0.73869782,
        0.86192188,  0.05410454,  0.67900499,  0.04968001,  0.01682169,
        0.68343166,  0.23725652,  0.60101072,  0.93540955,  0.91394071,
        0.42094008,  0.942845  ,  0.03707792,  0.88660158,  0.66692138,
        0.78639287,  0.77821242,  0.59697685,  0.18781059,  0.14406998,
        0.70678464,  0.52874776,  1.0214227 ,  0.91236132,  0.3466082 ,
        0.04581386,  0.01528511,  0.684978  ,  0.88431908,  0.54269719,
        0.24721297,  0.45795821,  0.81494595,  0.46887367,  0.78734269,
        0.25196784,  0.08862728, -0.09041561,  0.97589813,  0.0576208 ,
        1.11018478,  1.11359236,  0.90562135,  0.99986087,  0.53212273,
        0.30614883,  0.07344757,  0.66364374,  0.59819792,  0.29532152,
        0.97704977,  0.28076177,  0.57279473,  0.07787361,  0.45276559,
        0.28677426,  0.69596803,  0.64559973,  0.042946  ,  0.73044798,
        0.67940154,  0.09362414,  0.55526801,  0.1080068 ,  0.0691595 ,
        0.09923706,  0.93836693,  0.82612977,  0.19655942,  0.67288896,
        0.09757847,  1.04123081,  0.24119019,  0.97174872,  0.62076499,
        0.14681031,  1.11375986,  0.48506094,  0.07685138,  0.46406075,
        0.8723322 , -0.09242244,  0.49634277,  0.94872323,  0.22778507,
        0.67645234,  0.96882716,  0.13781916,  0.25794715,  0.83115405,
        0.18944306,  0.59952213,  0.08178897,  1.02408189,  0.50029087,
        0.85554712,  0.70837275,  0.30105752,  0.90288351,  0.08478451,
        0.07188065,  0.09646659,  0.44685945,  0.04083449,  0.35111088,
        0.30303556,  1.04848443,  0.78009395,  0.11406623,  1.15222873,
        0.11324037,  0.70328188,  0.64563861, -0.08327911,  0.61279581,
        0.31886203,  0.1494813 ,  1.0844825 ,  0.6355489 ,  0.8369182 ,
        0.88250924,  0.5999229 ,  0.02293207,  0.3076407 ,  0.24377221,
        0.03042953,  0.72381295,  0.85299304,  0.00300425,  0.77965593,
        0.12374126,  0.05019255,  0.24936684,  0.05525832,  0.84975662,
        0.06650223,  0.14635302,  0.79865408, -0.06190852,  0.70589518,
        0.91838982,  0.45482086,  0.85532952,  0.10303735,  0.25028265,
        0.81332101,  0.8975675 , -0.01812677,  0.79766566,  0.03624573,
        1.03134259,  0.4565149 ,  0.83343251,  0.21011031,  0.48051781,
        0.7645766 ,  1.02841351,  0.04180886,  1.01265509,  0.36857037,
        0.03464718,  1.04589654, -0.06716161,  0.91468318,  0.97407772,
        0.74847728,  0.88453607,  0.75635606, -0.0578664 ,  0.92038642,
        0.16644484,  0.09296502, -0.03369309,  1.11354525,  0.80672388,
        0.92773711,  0.34976637,  0.69434275,  0.86082245,  0.07149191,
        0.70799134,  0.18760849,  0.66869769,  0.80166119,  0.55425563,
        0.12477876,  0.20368394,  0.19909675,  1.06290162,  0.56315078,
        0.54237693,  1.08468923,  0.69168252,  0.01881462,  0.25261076,
        0.39431283,  0.83251638,  1.04017688, -0.03383058,  0.95148432,
       -0.08304709,  0.7577151 ,  0.58475365,  0.08933516,  0.32208319,
        1.10360179,  0.5814699 ,  0.28643528,  0.31227439,  0.43577382,
        1.01981866,  0.58479663,  0.53979103,  1.06294654,  0.95892063,
        0.45312058,  0.35708684,  0.63882568,  0.01561435,  0.95823437,
        0.73014505,  0.50328245,  0.12052727,  0.92718202,  0.7333934 ,
        0.01877417,  1.01134447,  0.9952469 ,  0.40550077,  0.84063687,
        0.7799688 ,  0.94417675,  0.80588307,  0.56450353,  0.59351463,
        0.17897358,  0.83744167,  0.32457489,  0.2923862 ,  0.65868118,
        0.09342545,  0.92697357,  0.87011171,  0.85046534,  1.22490878,
        0.64726031,  0.88705099,  0.08103804,  0.8455276 ,  0.79041601,
       -0.09657862,  0.27448116,  1.04566938,  0.88256869,  1.06240036,
        0.61150964,  0.90156673,  0.02990383,  0.30035479,  0.69562389,
        0.95132011,  0.48653386, -0.0466959 , -0.01405298,  0.07456081,
        0.08433113,  0.69623079,  0.16106299,  0.00410003,  0.8215906 ,
        0.28353688,  0.99371625,  0.42781695, -0.03626598, -0.14663421,
        0.37021484,  0.09066038,  0.93583912])

In [211]:
y_test

668    0
30     1
377    1
535    1
807    0
      ..
164    0
28     0
514    1
193    0
321    1
Name: HeartDisease, Length: 303, dtype: int64

In [212]:
r2 = r2_score(y_pred_lin_reg,y_test)

In [213]:
r2

0.19878957326662394

## creating logestic regression model

In [217]:
model_log_reg = LogisticRegression()
model_log_reg.fit(X_train,y_train)

LogisticRegression()

In [218]:
y_pred_log_reg = model_log_reg.predict(X_test)

In [219]:
y_pred_log_reg

array([0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1])

In [221]:
y_test

668    0
30     1
377    1
535    1
807    0
      ..
164    0
28     0
514    1
193    0
321    1
Name: HeartDisease, Length: 303, dtype: int64

In [222]:
r2= r2_score(y_pred_log_reg,y_test)

In [223]:
r2

0.45441370223978916

In [224]:
accuracy_score(y_pred_log_reg,y_test)

0.8646864686468647

In [225]:
accuracy_score(y_pred_log_reg,y_test)

0.8646864686468647

In [226]:
f1_score(y_pred_log_reg,y_test)

0.881159420289855

## creating naive bayes model

In [227]:
model_NB = GaussianNB()
model_NB.fit(X_train,y_train)

GaussianNB()

In [228]:
y_pred_NB = model_NB.predict(X_test)

In [229]:
y_pred_NB

array([0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1])

In [230]:
r2_score(y_pred_NB,y_test)

0.45560911481156885

In [231]:
accuracy_score(y_pred_NB,y_test)

0.8646864686468647

In [233]:
f1_score(y_pred_NB,y_test)

0.880466472303207

In [235]:
confusion_matrix(y_pred_NB,y_test)

array([[111,  29],
       [ 12, 151]])

In [237]:
print(classification_report(y_pred_NB,y_test))

              precision    recall  f1-score   support

           0       0.90      0.79      0.84       140
           1       0.84      0.93      0.88       163

    accuracy                           0.86       303
   macro avg       0.87      0.86      0.86       303
weighted avg       0.87      0.86      0.86       303