In [155]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [156]:
df = pd.read_csv(r'C:\CODING\practice for archived\anime.csv')

In [157]:
df.head()

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

In [158]:
df.isnull().sum()

anime_id      0
name          0
genre        62
type         25
episodes      0
rating      230
members       0
dtype: int64

In [159]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12294 entries, 0 to 12293
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   anime_id  12294 non-null  int64
 1   name      12294 non-null  str
 2   genre     12232 non-null  str
 3   type      12269 non-null  str
 4   episodes  12294 non-null  str
 5   rating    12064 non-null  float64
 6   members   12294 non-null  int64
dtypes: float64(1), int64(2), str(4)
memory usage: 672.5 KB

In [160]:
df[df['rating'].isnull()]

,anime_id,name,genre,type,episodes,rating,members
8968,34502,Inazma Delivery,"Action, Comedy, Sci-Fi",TV,10,NaN,32
9657,34309,Nananin no Ayakashi: Chimi Chimi Mouryou!! Gen...,"Comedy, Supernatural",TV,Unknown,NaN,129
10896,34096,Gintama (2017),"Action, Comedy, Historical, Parody, Samurai, S...",TV,Unknown,NaN,13383
10897,34134,One Punch Man 2,"Action, Comedy, Parody, Sci-Fi, Seinen, Super ...",TV,Unknown,NaN,90706
10898,30484,Steins;Gate 0,"Sci-Fi, Thriller",NaN,Unknown,NaN,60999
...,...,...,...,...,...,...,...
12274,34492,Nuki Doki! Tenshi to Akuma no Sakusei Battle -...,Hentai,OVA,Unknown,NaN,392
12279,34491,Sagurare Otome The Animation,Hentai,OVA,1,NaN,79
12280,34312,Saimin Class,Hentai,OVA,Unknown,NaN,240
12282,34388,Shikkoku no Shaga The Animation,Hentai,OVA,Unknown,NaN,195
12285,34399,Taimanin Asagi 3,"Demons, Hentai, Supernatural",OVA,Unknown,NaN,485

In [161]:
df

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
...,...,...,...,...,...,...,...
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211
12290,5543,Under World,Hentai,OVA,1,4.28,183
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142

In [162]:
df['rating'].mean()

np.float64(6.473901690981432)

In [163]:
df['rating'] = df['rating'].fillna(6.47)

In [164]:
df.isnull().sum()

anime_id     0
name         0
genre       62
type        25
episodes     0
rating       0
members      0
dtype: int64

In [165]:
df

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
...,...,...,...,...,...,...,...
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211
12290,5543,Under World,Hentai,OVA,1,4.28,183
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142

In [166]:
df['genre'].mode()[0]

'Hentai'

In [167]:
df['genre']=df['genre'].fillna('Hentai')

In [168]:
df

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
...,...,...,...,...,...,...,...
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211
12290,5543,Under World,Hentai,OVA,1,4.28,183
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142

In [169]:
df.isnull().sum()

anime_id     0
name         0
genre        0
type        25
episodes     0
rating       0
members      0
dtype: int64

In [170]:
df['type'].mode()[0]

'TV'

In [171]:
df['type'] = df['type'].fillna('TV')

In [172]:
df.isnull().sum()

anime_id    0
name        0
genre       0
type        0
episodes    0
rating      0
members     0
dtype: int64

## now doing data cleaning and preprocessing

In [173]:
x = df.drop(['rating'],axis= 1)
y = df['rating']

In [174]:
x

,anime_id,name,genre,type,episodes,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,151266
...,...,...,...,...,...,...
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,211
12290,5543,Under World,Hentai,OVA,1,183
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,219
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,175
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,142

In [175]:
y

0        9.37
1        9.26
2        9.25
3        9.17
4        9.16
         ...
12289    4.15
12290    4.28
12291    4.88
12292    4.98
12293    5.46
Name: rating, Length: 12294, dtype: float64

In [176]:
df.columns

Index(['anime_id', 'name', 'genre', 'type', 'episodes', 'rating', 'members'], dtype='str')

In [177]:
one_hot_encoding = pd.get_dummies(x,columns=['name','genre','type'],drop_first=True)

In [178]:
one_hot_encoding.head()

,anime_id,episodes,members,"name_&quot;Aesop&quot; no Ohanashi yori: Ushi to Kaeru, Yokubatta Inu",name_&quot;Bungaku Shoujo&quot; Kyou no Oyatsu: Hatsukoi,name_&quot;Bungaku Shoujo&quot; Memoire,name_&quot;Bungaku Shoujo&quot; Movie,name_&quot;Eiji&quot;,name_&quot;Eiyuu&quot; Kaitai,name_.hack//G.U. Returner,...,"genre_Super Power, Supernatural, Vampire",genre_Supernatural,genre_Thriller,genre_Vampire,genre_Yaoi,type_Music,type_ONA,type_OVA,type_Special,type_TV
0,32281,1,200630,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,5114,64,793665,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2,28977,51,114262,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3,9253,24,673572,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
4,9969,51,151266,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [187]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Create a sample DataFrame with many columns
df = pd.DataFrame({
    'anime_id': [1, 2, 3],
    'name': ['Anime A', 'Anime B', 'Anime C'],
    'genre': ['Action', 'Comedy', 'Drama'],
    'type': ['TV', 'Movie', 'OVA'],
    'episodes': [12, 24, 36],
    'members': [1000, 2000, 3000]
})

# Create a dictionary to store the encoders
encoders = {}
xlabel = x.copy()

# Apply LabelEncoder to each column and store in the dictionary
for col in df.columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    encoders[col] = le

print(df)
print(encoders)

   anime_id  name  genre  type  episodes  members
0         0     0      0     2         0        0
1         1     1      1     0         1        1
2         2     2      2     1         2        2
{'anime_id': LabelEncoder(), 'name': LabelEncoder(), 'genre': LabelEncoder(), 'type': LabelEncoder(), 'episodes': LabelEncoder(), 'members': LabelEncoder()}

In [188]:
df.head()

   anime_id  name  genre  type  episodes  members
0         0     0      0     2         0        0
1         1     1      1     0         1        1
2         2     2      2     1         2        2

## crating models

In [181]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score,root_mean_squared_error,f1_score,accuracy_score,confusion_matrix,classification_report
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

In [189]:
X_train, X_test, y_train, y_test = train_test_split(xlabel, y, test_size=0.33, random_state=42)

In [190]:
model_log = LogisticRegression()
model_log.fit(X_train,y_train)

ValueError: could not convert string to float: 'Ookii 1 Nensei to Chiisana 2 Nensei'